[build.environment]
  YARN_FLAGS='--pure-lockfile'
  REACT_APP_RECOVER_KOVAN_ADDRESS='0x5b10940344181487aa7827e6e6b8648eb707a8c0'
  REACT_APP_ARBITRATOR_KOVAN_ADDRESS='0x91be318eca5df3713551e8ae66735f1f1cea8cec'
  REACT_APP_WEB3_KOVAN_FALLBACK_URL='wss://kovan.infura.io/ws/v3/846256afe0ee40f0971d902ea8d36266'

[context.production.environment]
  REACT_APP_RECOVER_MAINNET_ADDRESS='0xe108942a97f02c21BAe85c3e16a3e58E8be2caB9'
  REACT_APP_ARBITRATOR_MAINNET_ADDRESS='0xd1b286456978dfcd8eac84dc801d98a48634ee32'
  REACT_APP_WEB3_MAINNET_FALLBACK_URL='wss://mainnet.infura.io/ws/v3/846256afe0ee40f0971d902ea8d36266'

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  publish = "build"
  functions = "lambda"